### ISSUE TITLE
Cannot connect to something with AceStream

### ISSUE THREAD

**Issue by alicerum** [1orgar/kodi#1]
Hey! I installed anidub addon on my openelec (on raspberry pi 3), and keep getting an error upon trying to open any anime title.
Log containing this:

```
03:53:14.605: TSENGINE: init...
03:53:48.995: TSENGINE: connection failed
03:53:50.103: TSENGINE: garbage collected: (289, 8, 0)
```

Any ideas what I could do to make it work?

**Comment by alicerum** [comment]
AceStream plugin shows port 62062 on localhost by default in settings. But telnet cannot open connection on this port.
Do I have to install some other addon?

**Comment by 1orgar** [comment]
You must install the AceStream application to your PI 3.
PS: AceStream not fully supported on pi 3 (functionality is not guaranteed), use another p2p engine in the plugin settings.

**Comment by alicerum** [comment]
Yeah, I installed AceStream from your repo, didn't help, unfortunately.
But another p2p engine (Py2http) works like a charm, thank you!

**Comment by 1orgar** [comment]
AceStream from my kodi repository is a client for the AceStream Media Service software which is installed separately on a device. https://twistedlinux.wordpress.com/2016/02/29/run-acestream-under-openelec-on-raspberry-pi-2/
PS. I don't recommend using Ace on PI

**Comment by alicerum** [comment]
@1orgar oh, i see now. Thank you! will try this later maybe. Since another p2p options do the trick, i'm really glad. Thank you for the great work on the add-on!
